Global:
  use_gpu: false
  # epoch_num: 50
  epoch_num: 200
  log_smooth_window: 20
  save_model_dir: ./output/custom_model
  # save_epoch_step: 10
  save_epoch_step: 1
  # eval_batch_step: [0, 100]
  eval_batch_step: [0, 2000]
  print_batch_step: 10
  character_dict_path: PaddleOCR/ppocr/utils/en_dict.txt
  # character_type: en
  max_text_length: 25
  use_space_char: False
  cal_metric_during_train: True
  pretained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: False   
  infer_img: 
  infer_mode: False
  save_res_path: ./output/rec/predicts_svtr.txt


Optimizer:
  name: AdamW
  beta1: 0.9
  beta2: 0.99
  epsilon: 0.00000008
  weight_decay: 0.05
  no_weight_decay_name: norm pos_embed
  one_dim_param_no_weight_decay: true
  lr:
    name: Cosine
    learning_rate: 0.00025
    warmup_epoch: 10

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./training_data/train
    label_file_list:
      - ./training_data/train/labels.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - RecAug: 
          rotate: [-5, 5]        # rotate slightly
          random_crop: true       # crop a bit to simulate zoom
          keep_ratio: true
          # color augmentations
          brightness: [0.8, 1.2]
          contrast: [0.8, 1.2]
          saturation: [0.8, 1.2]
          hue: [-0.05, 0.05]
          # small noise
          gaussian_noise: [0, 0.01]
        
      - CTCLabelEncode: {}
      - RecResizeImg:
          image_shape: [3, 48, 400]
          padding: False
      - KeepKeys:
          keep_keys: ["image", "label", "length"]

  loader:
    shuffle: true
    # batch_size_per_card: 32
    batch_size_per_card: 512
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./training_data/val
    label_file_list:
      - ./training_data/val/labels.txt
    ratio_list:
    - 0.1
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: {}
      - RecResizeImg:
          image_shape: [3, 48, 400]
          padding: False
      - KeepKeys:
          keep_keys: ["image", "label", "length"]

  loader:
    shuffle: False
    # batch_size_per_card: 32
    batch_size_per_card: 256

    drop_last: False
    num_workers: 2

Architecture:
  model_type: rec
  algorithm: SVTR
  Transform:
    name: STN_ON
    tps_inputsize: [32, 64]
    tps_outputsize: [32, 100]
    num_control_points: 20
    tps_margins: [0.05,0.05]
    stn_activation: none
  Backbone:
    name: SVTRNet
    img_size: [32, 100]
    out_char_num: 25
    out_channels: 192
    patch_merging: 'Conv'
    embed_dim: [64, 128, 256]
    depth: [3, 6, 3]
    num_heads: [2, 4, 8]
    mixer: ['Local','Local','Local','Local','Local','Local','Global','Global','Global','Global','Global','Global']
    local_mixer: [[7, 11], [7, 11], [7, 11]]
    last_stage: True
    prenorm: false
  Neck:
    name: SequenceEncoder
    encoder_type: reshape
    hidden_size: 48
  Head:
    name: CTCHead
    fc_decay: 0.00001
    out_channels: 95

Metric:
  name: RecMetric
  main_indicator: acc

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode
